Backend fetch, flera inputs, radiobuttons etc
JohanCodeForFun/JSU-VUE-LAB3 pull request #13
Opened 2023-03-01 13:06 UTC by DamirDervovic

2023-03-01 15:25 UTC, ElisNz reviewed
Bra jobbat!

2023-03-01 15:25 UTC, ElisNz commented on DAAJE/src/components/QuizForm.vue
> +                    this.showForm = false
Är koden nedan för att nollställa this.questions efter posten? Tror inte du behöver göra detta, men bara för att vara säker på att inte payloaden nollas innan promise är resolved och post requesten avslutad; använd gärna .then(this.questions = ...)

2023-03-01 15:25 UTC, ElisNz commented on DAAJE/src/components/QuizForm.vue
> +                    const response = await fetch(
Detta går bra. Jag skapar en ny handler imorgon förmiddag för att hantera denna post. Dock är det bra om du använder /post/ som prefix innan /createquiz (eller vilka andra posts som helst). Detta är för att jag gärna vill använda samma proxy adress till alla posts :)

2023-03-02 09:45 UTC, JohanCodeForFun requested changes
Hej Damir! 

Bra uttökning av quiz form input! Ett steg närmre fungerade quiz app.

Det jag undrar över är din addQuestion() method. Det ser ut som att du pushar in samma text element, med tomma strängar fyra gånger irad. Borde det inte vara ex, text1: textAnswer1 ?

Bra jobbat i övrigt!

2023-03-03 09:42 UTC, closed without merging